'use client'

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 robotic_arm.glb --transform 
Files: robotic_arm.glb [18MB] > /Users/valeriefuchs/Desktop/DEV/monumental/public/models/robotic_arm-transformed.glb [657KB] (96%)
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function RoboticArm(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/models/robotic_arm-transformed.glb')
  const { actions } = useAnimations(animations, group)

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Object_5" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Bone006_07" position={[0, 4.562, 5.244]} />
        </group>
        <group name="Bone_00">
          <group name="Bone001_01" position={[0, 0.864, 0]}>
            <group name="Bone002_02" position={[0, 2.872, 0]}>
              <group name="Bone003_03" position={[0, 3.064, 0]} rotation={[-1.57, 0, 0]}>
                <group name="Bone004_04" position={[0, 4.2, 0]} rotation={[-1.343, 0, 0]}>
                  <group name="Cylinder015">
                    <mesh name="Cylinder015_Material_0" geometry={nodes.Cylinder015_Material_0.geometry} material={materials.Material} />
                  </group>
                  <group name="Cylinder020" position={[0, 1.487, 0]}>
                    <mesh name="Cylinder020_Material_0" geometry={nodes.Cylinder020_Material_0.geometry} material={materials.Material} />
                  </group>
                  <group name="Cylinder021" position={[0, 1.487, 0]}>
                    <mesh name="Cylinder021_Material_0" geometry={nodes.Cylinder021_Material_0.geometry} material={materials.Material} />
                  </group>
                </group>
                <group name="Bone007_05" position={[0, 3.334, -0.73]} rotation={[-2.598, 0.017, 0]}>
                  <group name="Cylinder019" rotation={[2.609, 0.017, 0.005]}>
                    <mesh name="Cylinder019_Material_0" geometry={nodes.Cylinder019_Material_0.geometry} material={materials.Material} />
                  </group>
                </group>
                <group name="Cylinder014">
                  <mesh name="Cylinder014_Material_0" geometry={nodes.Cylinder014_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cylinder018" position={[0, 3.334, -0.73]}>
                  <mesh name="Cylinder018_Material_0" geometry={nodes.Cylinder018_Material_0.geometry} material={materials.Material} />
                </group>
                <group name="Cylinder004_Plate001">
                  <mesh name="Cylinder004_Plate001_Material_0" geometry={nodes.Cylinder004_Plate001_Material_0.geometry} material={materials.Material} />
                </group>
              </group>
              <group name="Bone005_06" position={[0, 0.864, -0.9]} rotation={[-1.027, -0.001, 0]}>
                <group name="Cylinder016" position={[0, 0.005, -0.004]} rotation={[-0.56, -0.001, 0.004]}>
                  <mesh name="Cylinder016_Material_0" geometry={nodes.Cylinder016_Material_0.geometry} material={materials.Material} />
                </group>
              </group>
              <group name="Cylinder013" position={[0, -0.036, 0]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh name="Cylinder013_Material_0" geometry={nodes.Cylinder013_Material_0.geometry} material={materials.Material} />
              </group>
              <group name="Cylinder017" position={[0, 0.863, -0.906]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh name="Cylinder017_Material_0" geometry={nodes.Cylinder017_Material_0.geometry} material={materials.Material} />
              </group>
            </group>
            <group name="Cylinder011" position={[0, 0.225, 0]} rotation={[-Math.PI / 2, 0, 0]}>
              <mesh name="Cylinder011_Material_0" geometry={nodes.Cylinder011_Material_0.geometry} material={materials.Material} />
            </group>
            <group name="Cylinder012" position={[0, 2.872, 0]} rotation={[-Math.PI / 2, 0, 0]}>
              <mesh name="Cylinder012_Material_0" geometry={nodes.Cylinder012_Material_0.geometry} material={materials.Material} />
            </group>
          </group>
        </group>
        <mesh name="Cylinder010_Material_0" geometry={nodes.Cylinder010_Material_0.geometry} material={materials.Material} position={[0, 0.5, 0]} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
    </group >
  )
}

useGLTF.preload('/models/robotic_arm-transformed.glb')
