/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

'use client'

import React, { useEffect } from 'react'
import { PerspectiveCamera, OrbitControls, Center } from '@react-three/drei'
import { Canvas } from '@react-three/fiber'
import { RoboticArm } from '@/components/Preview/RoboticArm'

export function Scene(props) {

  return (
    <Canvas>
      <ambientLight intensity={0.5} />
      <directionalLight
        position={[2, 5, 2]}
        intensity={1.2}
        castShadow
        shadow-mapSize-width={2048}
        shadow-mapSize-height={2048}
      />
      <pointLight position={[-2, -2, 2]} intensity={0.5} />
      <PerspectiveCamera makeDefault position={[0, 0, 15]} />

      <Center>
        <RoboticArm position={[0, 0, 0]} rotation={[0, -1.7, 0]} />
      </Center>

      {/* <OrbitControls /> */}
    </Canvas >
  )
}



