/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

'use client'

import React, { useEffect } from 'react'
import { useGLTF, PerspectiveCamera, OrbitControls } from '@react-three/drei'
import { Canvas } from '@react-three/fiber'

export function Scene(props) {
  const { nodes, materials } = useGLTF('/models/helmet-transformed.glb')

  return (
    <Canvas>
      <ambientLight intensity={10} position={[100, 50, 100]} rotation={[0, 0, 0]} />
      <PerspectiveCamera makeDefault position={[0, 0, 3]} />
      <group {...props}>
        <mesh
          geometry={nodes['node_damagedHelmet_-6514'].geometry}
          material={materials.Material_MR}
          rotation={[Math.PI / 2, 0, 0]} />
      </group>
      <OrbitControls />
    </Canvas>
  )
}

useGLTF.preload('/helmet-transformed.glb')


