/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

'use client'

import React, { useEffect } from 'react'
import { PerspectiveCamera, OrbitControls, Center } from '@react-three/drei'
import { Canvas } from '@react-three/fiber'
import { RoboticArm } from '@/components/Preview/RoboticArm'

export function Scene() {

  return (
    <Canvas>
      <ambientLight color="white" intensity={2} />
      <directionalLight
        color="white"
        intensity={2}
      />
      {/* <pointLight position={[-2, -2, 2]} intensity={2} /> */}
      <PerspectiveCamera makeDefault position={[0, 0, 15]} />

      <Center>
        <RoboticArm position={[0, 0, 0]} />
      </Center>

      {/* <OrbitControls /> */}
    </Canvas >
  )
}



